"""Multi-seed sweep for the headline experiments, with mean +/- std aggregation.

The paper's Tables II/III and the hard-negative claim are single-seed (seed 0).
Robustness claims require seed confidence intervals,
especially for the DRO-vs-balanced verdict and the 25.3% false-positive reduction.
This driver reruns the three headline experiments over several seeds, aggregates
mean +/- std, and emits:

  * seeds_report.json  -- per-seed reports + aggregate for each experiment
  * seeds_report.md    -- human-readable tables (mean +/- std)
  * seeds_tables.tex   -- drop-in LaTeX for the two headline tables with CIs

Run it with the SAME config used for the reported numbers. This must be the GPU
preset with the real DINOv2 verifier -- a stub run is not a reportable
FM-RobustAFB result (see scripts/run_all.py).

Example (GPU, real verifier, 5 seeds):

  python scripts/run_seeds.py --config configs/raw_sputum.yaml \\
      --seeds 0 1 2 3 4 --out runs/seeds \\
      detector.backbone=resnet50 detector.pretrained=True \\
      verifier.offline_stub=False train.epochs=24

The detector is retrained per seed (that is the point -- initialization and
data-order variance is what the CIs capture), so this is expensive; budget
accordingly.
"""
from __future__ import annotations

import argparse
import json
import time
from pathlib import Path

import numpy as np

from fm_robustafb.config import load_config
from fm_robustafb.experiments import REGISTRY
from fm_robustafb.experiments.common import (
    aggregate_runs, aggregate_seeds, clone_config, report_to_markdown,
)
from fm_robustafb.utils.logging import get_logger

logger = get_logger("run_seeds")

# Experiment -> run-kwargs for the headline set. Only the three the paper leads on.
HEADLINE = {
    "benchmark": {},        # table-shaped: one row per group-robust variant
    "calibration": {},      # flat dict: D-ECE, LaECE, AUROC, risk-coverage, ...
    "hard_negative": {},    # flat dict: fp_reduction_fraction, rejection accuracy
}


def _run_experiment_over_seeds(name: str, cfg, seeds, run_kwargs) -> dict:
    run_fn = REGISTRY[name]
    reports = []
    for s in seeds:
        c = clone_config(cfg)
        c.seed = s
        t0 = time.time()
        rep = run_fn(c, **run_kwargs)
        rep["_seed"] = s
        reports.append(rep)
        logger.info("[%s] seed %d done in %.1f min", name, s, (time.time() - t0) / 60)
    # Table-shaped reports (benchmark) aggregate per variant; flat reports per key.
    if all("table" in r for r in reports):
        agg = aggregate_runs(reports)
    else:
        agg = {"per_seed": reports, "aggregate": aggregate_seeds(reports)}
    return agg


def _fmt(mean: float, std: float, digits: int = 3) -> str:
    if mean is None or (isinstance(mean, float) and np.isnan(mean)):
        return "---"
    return f"{mean:.{digits}f} $\\pm$ {std:.{digits}f}"


def _latex_benchmark(agg: dict) -> str:
    """Rebuild Table II (group-robust benchmark) with per-seed CIs."""
    rows = {r["variant"]: r for r in agg["aggregate"]["table"]}
    order = ["detector_erm", "detector_group_balanced", "detector_group_dro",
             "full_fm_robustafb"]
    pretty = {
        "detector_erm": "ERM (no verifier)",
        "detector_group_balanced": "Group-balanced (no verifier)",
        "detector_group_dro": "Group DRO (no verifier)",
        "full_fm_robustafb": "\\textbf{Full FM-RobustAFB}",
    }
    lines = [
        "% Auto-generated by scripts/run_seeds.py -- paste into main.tex (Table II).",
        "\\begin{tabular}{lcc}", "\\toprule",
        "Method & $\\wgap$ & mean AP$_{50}$ \\\\", "\\midrule",
    ]
    for k in order:
        r = rows.get(k)
        if r is None:
            continue
        wg = r.get("worst_group_AP50", {})
        mn = r.get("mean_AP50", {})
        lines.append(
            f"{pretty[k]} & {_fmt(wg.get('mean'), wg.get('std'))} & "
            f"{_fmt(mn.get('mean'), mn.get('std'))} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines)


def _latex_scalars(agg: dict, keys: list[tuple[str, str]]) -> str:
    """Emit a two-column mean +/- std table for selected flattened metric keys."""
    a = agg["aggregate"]
    lines = [
        "% Auto-generated by scripts/run_seeds.py.",
        "\\begin{tabular}{lc}", "\\toprule",
        "Metric & Value (mean $\\pm$ std) \\\\", "\\midrule",
    ]
    for key, label in keys:
        m = a.get(key)
        if m is None:
            lines.append(f"{label} & --- \\\\")
        else:
            lines.append(f"{label} & {_fmt(m['mean'], m['std'])} (n={m['n']}) \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--config", default="configs/raw_sputum.yaml")
    ap.add_argument("--seeds", type=int, nargs="+", default=None,
                    help="seeds to sweep; defaults to cfg.eval.seeds")
    ap.add_argument("--out", default="runs/seeds")
    ap.add_argument("--experiments", nargs="+", default=list(HEADLINE),
                    choices=list(HEADLINE), help="subset of headline experiments")
    ap.add_argument("--train-fraction", type=float, default=1.0)
    ap.add_argument("--verifier-epochs", type=int, default=5)
    ap.add_argument("opts", nargs="*", help="config overrides key.subkey=value")
    args = ap.parse_args()

    cfg = load_config(args.config, args.opts)
    seeds = args.seeds if args.seeds is not None else list(cfg.eval.seeds)
    if len(seeds) < 3:
        logger.warning("only %d seed(s); >=3 recommended for meaningful CIs", len(seeds))
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    logger.info("seed sweep: config=%s seeds=%s experiments=%s",
                args.config, seeds, args.experiments)

    common_kwargs = {"train_image_fraction": args.train_fraction}
    results: dict[str, dict] = {}
    md_parts: list[str] = [f"# Multi-seed sweep (seeds={seeds})\n"]
    t_start = time.time()
    for name in args.experiments:
        kwargs = dict(HEADLINE[name])
        kwargs.update(common_kwargs)
        if name in ("benchmark",):
            kwargs["verifier_epochs"] = args.verifier_epochs
        agg = _run_experiment_over_seeds(name, cfg, seeds, kwargs)
        results[name] = agg
        # Human-readable block.
        if "table" in agg.get("aggregate", {}):
            md_parts.append(report_to_markdown(agg, title=f"{name} (mean +/- std)"))
        else:
            md_parts.append(f"## {name} (mean +/- std)\n")
            for k, v in sorted(agg["aggregate"].items()):
                md_parts.append(f"- `{k}`: {v['mean']:.4f} +/- {v['std']:.4f} (n={v['n']})")
            md_parts.append("")
        # Checkpoint after each experiment so a crash keeps finished work.
        (out / "seeds_report.json").write_text(json.dumps(results, indent=2, default=str))

    (out / "seeds_report.md").write_text("\n".join(md_parts))

    # LaTeX snippets for the two headline tables.
    tex_parts = []
    if "benchmark" in results:
        tex_parts.append(_latex_benchmark(results["benchmark"]))
    if "calibration" in results:
        tex_parts.append(_latex_scalars(results["calibration"], [
            ("clean.calibration.D-ECE", "D-ECE (global)"),
            ("clean.calibration.worst_group_D-ECE", "D-ECE (worst group)"),
            ("clean.calibration.LaECE", "LaECE"),
            ("clean.calibration.brier", "Brier"),
            ("clean.calibration.nll", "NLL"),
            ("clean.selective.failure_detection.AUROC", "Failure AUROC"),
            ("clean.selective.AURC", "AURC"),
        ]))
    if "hard_negative" in results:
        tex_parts.append(_latex_scalars(results["hard_negative"], [
            ("fp_reduction_fraction", "FP reduction (fraction)"),
            ("hard_negative_rejection_accuracy", "Hard-negative rejection acc."),
        ]))
    (out / "seeds_tables.tex").write_text("\n\n".join(tex_parts))

    logger.info("sweep done in %.1f min; wrote %s/{seeds_report.json,seeds_report.md,seeds_tables.tex}",
                (time.time() - t_start) / 60, out)
    print("\n".join(md_parts))


if __name__ == "__main__":
    main()
